server:
  port: 8082
  servlet: 
    contextPath: /user-role-api
  
logging:
  level:
    org:
      springframework: ERROR
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: root
  jpa:
    generate-ddl: true 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
  view:
    prefix: app
mysql:
  schema: dev